# Generated by Django 3.0.7 on 2020-07-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20200707_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='view_counter',
            field=models.IntegerField(null=True),
        ),
    ]
