# Generated by Django 3.0.7 on 2020-07-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20200707_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='view_counter',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
